### ISSUE TITLE
HTML Validation Issues

### ISSUE THREAD

**Issue by neilmispelaar** [imd1005-web-development-winter-2023/assignment-02-garnkai#2]
Hi @garnkai 

Really great work so far on your submission for Assignment 02 🎉! Well done. 

I know your web page is still in flight, but wanted to bring up a couple of items.

## Issue Description

I ran your code through the HTML Validator and there are two small errors being thrown (don't worry about the warnings / info items that come back).

## HTML Validator Results

Here is the link to the full results:

https://validator.w3.org/nu/?doc=https%3A%2F%2Fimd1005-web-development-winter-2023.github.io%2Fassignment-02-garnkai%2F

## Screenshot

<img width="1417" alt="Screenshot 2023-02-23 at 9 02 19 PM" src="https://user-images.githubusercontent.com/9325038/221073846-56a28003-8084-44b3-8adc-c2326490384e.png">

**Comment by garnkai** [comment]
> Hi @garnkai
> 
> Really great work so far on your submission for Assignment 02 🎉! Well done.
> 
> I know your web page is still in flight, but wanted to bring up a couple of items.
> 
> ## Issue Description
> I ran your code through the HTML Validator and there are two small errors being thrown (don't worry about the warnings / info items that come back).
> 
> ## HTML Validator Results
> Here is the link to the full results:
> 
> https://validator.w3.org/nu/?doc=https%3A%2F%2Fimd1005-web-development-winter-2023.github.io%2Fassignment-02-garnkai%2F
> 
> ## Screenshot
> <img alt="Screenshot 2023-02-23 at 9 02 19 PM" width="1417" src="https://user-images.githubusercontent.com/9325038/221073846-56a28003-8084-44b3-8adc-c2326490384e.png">

Thank you for letting me know! I have made the changes :)
